export const ROUTES = {
  LOGIN:           '/login',
  CHANGE_PASSWORD: '/changer-mot-de-passe',
  DASHBOARD:       '/',
  VENDEURS:        '/vendeurs',
  ACHETEURS:       '/acheteurs',
  PRODUITS:        '/produits',
  CATEGORIES:      '/categories',
  COMMANDES:       '/commandes',
  PAIEMENTS:       '/paiements',
  ABONNEMENTS:     '/abonnements',
  MODERATION:      '/moderation',
  NOTIFICATIONS:   '/notifications',
  SIGNALEMENTS:    '/signalements',
  ADMINS:          '/admins',
  MENUS:           '/menus',
  CONFIG:          '/config',
};
