export const ROUTES = {
  LOGIN:           '/login',
  CHANGE_PASSWORD: '/changer-mot-de-passe',
  DASHBOARD:       '/',
  VENDEURS:        '/vendeurs',
  ACHETEURS:       '/acheteurs',
  PRODUITS:        '/produits',
  CATEGORIES:      '/categories',
  SIGNALEMENTS:    '/signalements',
  ADMINS:          '/admins',
  MENUS:           '/menus',
  CONFIG:          '/config',
  MESSAGES:        '/messages',
  COMMANDES:       '/commandes',
  ABONNEMENTS:     '/abonnements',
  PAIEMENTS:       '/paiements',
  RETOURS:         '/retours',
  AUDIT_LOGS:      '/audit-logs',
  NOTIFICATION_GLOBALE: '/notification-globale',
};
